### PR TITLE
init(.pkg): update nigiri commit to dump round times branch

### PR DESCRIPTION
**Pull request by Kvnstrck**
Update the nigiri base repository to the version agreed upon with AG

### CODE REVIEW

**Review by Kha1r0 — APPROVED** [review]
LGTM

**Review by nicosvv — APPROVED** [review]
LGTM too

**Review by D3vZro — APPROVED** [review]

**Review by MoPhliFra — COMMENTED** [review]
gut

**Comment by MoPhliFra** [comment]
richtig

**Review by MoPhliFra — APPROVED** [review]
alkjsdfgoöa jdföglmsadfg

**Comment by MoPhliFra** [comment]
gugu gaga

**Pull request merged**
